### ISSUE TITLE
eager for generated features

### ISSUE THREAD

**Issue by Zyf9909093** [chow-vincent/tennis_action_recognition#4]
I can't generate features with the **extract_and_save_sequences.ipynb** file, it bothers me for a long time. Could you send me the already generated features? Appreciate!
email: zyf_van0903@163.com

**Comment by chow-vincent** [comment]
I just updated the repo, see the latest commit for some of the main issues I fixed:

1. Make sure VIDEO_RGB is organized into consolidated folders: `backhand`, `forehand`, `bvolley`, `fvolley`, `service`, `smash` in order to match `data_file.csv`. 
2. Due to updates to the InceptionV3 API, I fixed some code in `extract_and_save_sequences.ipynb` so the model accepts image inputs of size 480 x 640 x 3.

Try the script now and lmk if u run into issues.
